backend:
  name: github
  repo: Turutupa/alblog
  branch: main

media_folder: content/assets
public_folder: ../assets

collections:
  - name: dogs
    label: Dogs
    folder: content/blog/dogs
    create: true
    category: dogs
    fields:
      - { name: 'title', label: 'Title' }
      - { name: 'date', label: 'Date', widget: 'date' }
      - { name: 'category', label: 'Category', default: 'dogs' }
      - { name: 'draft', label: 'Draft', widget: 'boolean', default: false }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: finance
    label: Finance
    folder: content/blog/finance
    create: true
    fields:
      - { name: 'title', label: 'Title' }
      - { name: 'date', label: 'Date', widget: 'date' }
      - { name: 'category', label: 'Category', default: 'finance' }
      - { name: 'draft', label: 'Draft', widget: 'boolean', default: false }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: life
    label: Life
    folder: content/blog/life
    create: true
    fields:
      - { name: 'title', label: 'Title' }
      - { name: 'date', label: 'Date', widget: 'date' }
      - { name: 'category', label: 'Category', default: 'life' }
      - { name: 'draft', label: 'Draft', widget: 'boolean', required: false }
      - { name: 'body', label: 'Body', widget: 'markdown' }
